### ISSUE TITLE
Internal Error when streaming comments

### ISSUE THREAD

**Issue by KylePiira** [steemit/steem-python#119]
Getting this error when using stream_comments() also getting a similar error when using other Blockchain module actions. Tested on multiple networks. 

```python
>>> from steem import Steem
>>> s = Steem(nodes=['https://api.steemit.com'])
>>> for post in s.stream_comments():
...     print(post.title)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kyle/Code/Django/env/local/lib/python3.6/site-packages/steem/steemd.py", line 132, in stream_comments
    ).stream("comment", *args, **kwargs):
  File "/home/kyle/Code/Django/env/local/lib/python3.6/site-packages/steem/blockchain.py", line 177, in stream
    for ops in self.stream_from(*args, **kwargs):
  File "/home/kyle/Code/Django/env/local/lib/python3.6/site-packages/steem/blockchain.py", line 74, in stream_from
    head_block = self.get_current_block_num()
  File "/home/kyle/Code/Django/env/local/lib/python3.6/site-packages/steem/blockchain.py", line 42, in get_current_block_num
    return self.info().get(self.mode)
  File "/home/kyle/Code/Django/env/local/lib/python3.6/site-packages/steem/blockchain.py", line 34, in info
    return self.steem.get_dynamic_global_properties()
  File "/home/kyle/Code/Django/env/local/lib/python3.6/site-packages/steem/steemd.py", line 410, in get_dynamic_global_properties
    return self.exec('get_dynamic_global_properties', api='database_api')
  File "/home/kyle/Code/Django/env/local/lib/python3.6/site-packages/steembase/http_client.py", line 186, in exec
    return_with_args=return_with_args)
  File "/home/kyle/Code/Django/env/local/lib/python3.6/site-packages/steembase/http_client.py", line 206, in _return
    raise RPCError(error_message)
steembase.exceptions.RPCError: Internal Error

```

**Comment by KylePiira** [comment]
I'm closing this as potential duplicate of https://github.com/steemit/steem-python/issues/108
