### ISSUE TITLE
Fail to import steem, SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mostar** [steemit/steem-python#140]
Hello,

After fresh install following "Installation with pipenv"

I fail to run the example scripts in: http://steem.readthedocs.io/en/latest/examples.html

all fail on 

`from steem import Steem`

python
Python 3.4.5 (default, May 29 2017, 15:17:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from steem import Steem

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/osboxes/steem-python/steem/__init__.py", line 2, in <module>
    from .steem import Steem
  File "/home/osboxes/steem-python/steem/steem.py", line 1, in <module>
    from .commit import Commit
  File "/home/osboxes/steem-python/steem/commit.py", line 15, in <module>
    from .account import Account
  File "/home/osboxes/steem-python/steem/account.py", line 237
    **self,
     ^
SyntaxError: invalid syntax

**Comment by cyon1c** [comment]
You are using Python 3.4.5 - try upgrading your environment to use 3.6.4. Development is currently in progress to bring compatibility across Python versions.

**Comment by cyon1c** [comment]
`steem-python` now supports Python 2.7 and Python 3.6. Closing this issue.
