### ISSUE TITLE
Why not create newaccount?

### ISSUE THREAD

**Issue by makarowdmitry** [steemit/steem-python#16]
I have error:

```
Traceback (most recent call last):
  File "/usr/local/bin/steempy", line 11, in <module>
    sys.exit(legacy())
  File "/usr/local/lib/python3.5/dist-packages/steem/cli.py", line 1282, in legacy
    delegation_fee_steem=args.fee,
  File "/usr/local/lib/python3.5/dist-packages/steem/commit.py", line 484, in create_account
    self.wallet.addPrivateKey(active_privkey)
  File "/usr/local/lib/python3.5/dist-packages/steem/wallet.py", line 212, in addPrivateKey
    self.keyStorage.add(self.encrypt_wif(wif), pub)
  File "/usr/local/lib/python3.5/dist-packages/steem/wallet.py", line 151, in encrypt_wif
    self.unlock()
  File "/usr/local/lib/python3.5/dist-packages/steem/wallet.py", line 100, in unlock
    masterpwd = self.MasterPassword(pwd)
  File "/usr/local/lib/python3.5/dist-packages/steembase/storage.py", line 401, in __init__
    self.decryptEncryptedMaster()
  File "/usr/local/lib/python3.5/dist-packages/steembase/storage.py", line 413, in decryptEncryptedMaster
    raise WrongMasterPasswordException
steembase.storage.WrongMasterPasswordException

```

I tested command:

1.
steempy newaccount divali8 --account furion --fee "9 STEEM"

2.
steempy newaccount divali888 --account steemy

3.
steempy newaccount divali888 

I used pass example
P5KQK4iogQypqYAzXbHWmhbwxddVFz8Xhg69czjKLDVhKwEQT2KY - use online generate
mp903804124

My OS
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

Python 
Python 3.6.1 :: Anaconda 4.4.0 (64-bit)

Please help me
))

**Comment by Netherdrake** [comment]
I am not sure what are you trying to do here.

`steembase.storage.WrongMasterPasswordException` means that your offline storage wallet password (this is not your steem key/password) is incorrect. You are asked to pick a password the first time you import an account into `steempy`. This is the password that is also required every time you want to use the local wallet.

**Comment by makarowdmitry** [comment]
I did not create passwords, accounts in steempy.
I want to create a new account for steemit.com.

My first command was for this:

`steempy newaccount merlo8901 --account steempy
`
http://joxi.ru/DmBgabzhXYad2P?d=1

But the account was not created.

Tell me how to create an account for steemit.com using steempy.
Thanks

**Comment by Netherdrake** [comment]
You need an account with some liquid STEEM to create an account.

**Comment by makarowdmitry** [comment]
For example, like this?
`steempy newaccount divali1234 --account  dinoo --fee "1 STEEM"`

dinoo  have STEEM
http://joxi.ru/82QjgPOHPNXBAd?d=1

Error again 
http://joxi.ru/krDg3Yjh19e5Ap?d=1

**Comment by Netherdrake** [comment]
Here is a step by step requirement.

1.) Import your existing account (dinoo) into steempy
2.) Set local wallet password (this should happen automatically in step 1), you can set env variable `UNLOCK` to avoid being prompted for pw every time.
3.) Run steempy newaccount

**Comment by makarowdmitry** [comment]
I took all the steps.
1. Imported account
2. Run creation new account.

everything is ok!

I have a question:
1. Minimum account_creation_fee in steempy 1 STEEM?
2. Can I create account without fee or with official account_creation_fee: 0.200 STEEM? How to do it?

I tried to do without fee and got an exception:
```
Traceback (most recent call last):
  File "/usr/local/bin/steempy", line 11, in <module>
    sys.exit(legacy())
  File "/usr/local/lib/python3.5/dist-packages/steem/cli.py", line 1282, in legacy
    delegation_fee_steem=args.fee,
  File "/usr/local/lib/python3.5/dist-packages/steem/commit.py", line 563, in create_account
    return self.finalizeOp(op, creator, "active")
  File "/usr/local/lib/python3.5/dist-packages/steem/commit.py", line 128, in finalizeOp
    return tx.broadcast()
  File "/usr/local/lib/python3.5/dist-packages/steem/transactionbuilder.py", line 131, in broadcast
    raise e
  File "/usr/local/lib/python3.5/dist-packages/steem/transactionbuilder.py", line 129, in broadcast
    self.steemd.broadcast_transaction(self.json())
  File "/usr/local/lib/python3.5/dist-packages/steem/steemd.py", line 860, in broadcast_transaction
    return self.exec('broadcast_transaction', signed_transaction, api='network_broadcast_api')
  File "/usr/local/lib/python3.5/dist-packages/steembase/http_client.py", line 186, in exec
    return_with_args=return_with_args)
  File "/usr/local/lib/python3.5/dist-packages/steembase/http_client.py", line 206, in _return
    raise RPCError(error_message)
steembase.exceptions.RPCError: 10 assert_exception: Assert Exception
creator.balance >= o.fee: Insufficient balance to create account.
    {"creator.balance":"0.640 STEEM","required":"6.000 STEEM"}
```
