### ISSUE TITLE
Cannot Customize Steem(nodes)

### ISSUE THREAD

**Issue by clayop** [steemit/steem-python#162]
When I add a my own node (e.g. `127.0.0.1:8090`) it gives the following error

```
Bad Cast:Invalid cast from type 'array_type' to Object
```

**Comment by cyon1c** [comment]
Could you please provide a full stack trace for the error?

**Comment by clayop** [comment]
```
>>> steemnode
'127.0.0.1:8090'
>>> steem = Steem(nodes=[steemnode], keys=[wif])
>>> bh = steem.get_dynamic_global_properties()["head_block_number"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/steem/steemd.py", line 413, in get_dynamic_global_properties
    return self.exec('get_dynamic_global_properties', api='database_api')
  File "/usr/local/lib/python3.5/dist-packages/steembase/http_client.py", line 186, in exec
    return_with_args=return_with_args)
  File "/usr/local/lib/python3.5/dist-packages/steembase/http_client.py", line 206, in _return
    raise RPCError(error_message)
steembase.exceptions.RPCError: Bad Cast:Invalid cast from type 'array_type' to Object
```

**Comment by roadscape** [comment]
Hey @clayop could you try again using latest master?
