### ISSUE TITLE
witnessupdate causes "Bad Cast:Invalid cast from string_type to Array" error

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/steem-python#193]
Trying to run this command:
` steempy witnessupdate --witness witnessname --signing_key STM.....`
Tried other non-steemit nodes to no avail, e.g.
` steempy --node https://rpc.buildteam.io witnessupdate --witness witnessname --signing_key STM.....`

Gives this error:
>Traceback (most recent call last):
  File "/usr/local/bin/steempy", line 9, in <module>
    load_entry_point('steem==1.0.0', 'console_scripts', 'steempy')()
  File "/usr/local/lib/python3.5/dist-packages/steem-1.0.0-py3.5.egg/steem/cli.py", line 1299, in legacyentry
  File "/usr/local/lib/python3.5/dist-packages/steem-1.0.0-py3.5.egg/steem/commit.py", line 1004, in witness_update
  File "/usr/local/lib/python3.5/dist-packages/steem-1.0.0-py3.5.egg/steem/commit.py", line 134, in finalizeOp
  File "/usr/local/lib/python3.5/dist-packages/steem-1.0.0-py3.5.egg/steem/transactionbuilder.py", line 139, in broadcast
  File "/usr/local/lib/python3.5/dist-packages/steem-1.0.0-py3.5.egg/steem/transactionbuilder.py", line 136, in broadcast
  File "/usr/local/lib/python3.5/dist-packages/steem-1.0.0-py3.5.egg/steem/steemd.py", line 754, in verify_authority
  File "/usr/local/lib/python3.5/dist-packages/steem-1.0.0-py3.5.egg/steembase/http_client.py", line 243, in call
  File "/usr/local/lib/python3.5/dist-packages/steem-1.0.0-py3.5.egg/steembase/http_client.py", line 263, in _return
steembase.exceptions.RPCError: Bad Cast:Invalid cast from string_type to Array```

**Comment by bobinson** [comment]
error seems to same as #191

**Comment by roadscape** [comment]
There were 2 bugs here; one is resolved, the other is an api issue which will be fixed soon.
