### ISSUE TITLE
TypeError while creating Steem object

### ISSUE THREAD

**Issue by AmoghSubhedar** [steemit/steem-python#224]
When I am creating a Steem object, I get this error:
```
    s = Steem(nodes=nds,no_broadcast=False, keys=['5Ui'])
  File "/home/ubuntu/.local/lib/python3.5/site-packages/steem/steem.py", line 60, in __init__
    steemd_instance=self.steemd, no_broadcast=no_broadcast, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/steem/commit.py", line 96, in __init__
    self.wallet = Wallet(self.steemd, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/steem/wallet.py", line 61, in __init__
    self.prefix = self.steemd.chain_params["prefix"]
  File "/home/ubuntu/.local/lib/python3.5/site-packages/steem/steemd.py", line 70, in chain_params
    chain = props["current_supply"].split(" ")[1]
TypeError: 'NoneType' object is not subscriptable
```
I've been using the same statement for creating Steem objects before and it used to work fine. This has only been a recent problem.

**Comment by mtastafford** [comment]
It looks like this just started happening for me as well -- not sure what the issue is. Occurs when calling any steempy commands (eg. "steempy listaccounts") as well.

**Comment by cyon1c** [comment]
@AmoghSubhedar @mtastafford could you provide a full bug report, including:

1. Version of Python you are running
2. Version of steem-python you are running
3. Expected Behavior
4. Actual Behavior 
5. Steps to reproduce
6. Stack Trace

`steem-python` is currently undergoing a significant face-lift, we'll address these issues asap.

**Comment by AmoghSubhedar** [comment]
1. Python 3.5.2
2. Not sure, but I remember updating it last week, when I first encountered this issue.
3. Should just create a Steem object and no error should be thrown
4. Throws a TypeError
5. s = Steem()
Traceback:
`    s = Steem(nodes=nds,no_broadcast=False, keys=['5Ui'])
  File "/home/ubuntu/.local/lib/python3.5/site-packages/steem/steem.py", line 60, in __init__
    steemd_instance=self.steemd, no_broadcast=no_broadcast, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/steem/commit.py", line 96, in __init__
    self.wallet = Wallet(self.steemd, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/steem/wallet.py", line 61, in __init__
    self.prefix = self.steemd.chain_params["prefix"]
  File "/home/ubuntu/.local/lib/python3.5/site-packages/steem/steemd.py", line 70, in chain_params
    chain = props["current_supply"].split(" ")[1]
TypeError: 'NoneType' object is not subscriptable`

**Comment by mtastafford** [comment]
1. Python 3.6.5;
2. steempy 1.0.0 & steem-python v '0.18.103';
3. Just about anything. Can't do much of anything. Not very helpful. Crashes on line "s = Steem()";
4. "steempy set nodes https://rpc.steemviz.com";
5.
```
>>> s = Steem()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mark/steem/lib64/python3.6/site-packages/steem/steem.py", line 60, in __init__
    steemd_instance=self.steemd, no_broadcast=no_broadcast, **kwargs)
  File "/home/mark/steem/lib64/python3.6/site-packages/steem/commit.py", line 96, in __init__
    self.wallet = Wallet(self.steemd, **kwargs)
  File "/home/mark/steem/lib64/python3.6/site-packages/steem/wallet.py", line 61, in __init__
    self.prefix = self.steemd.chain_params["prefix"]
  File "/home/mark/steem/lib64/python3.6/site-packages/steem/steemd.py", line 70, in chain_params
    chain = props["current_supply"].split(" ")[1]
TypeError: 'NoneType' object is not subscriptable
>>> 
```

**Comment by ArtoLabs** [comment]
### I can reproduce these errors on all three of my Ubuntu 16.04 servers.

This is an intermittent error that occurs when attempting to connect to the following steemd public websocket nodes:

	https://steemd.privex.io
            https://steemd.steemgigs.org
	rpc.steemliberator.com
	https://steemd.minnowsupportproject.org

Other nodes may be resulting in errors but these are the only ones I've tried. 

#### When running the following script:

```
#!/usr/bin/python

from steem import Steem

nodes = ['https://steemd.privex.io',
            'https://steemd.steemgigs.org',
	'rpc.steemliberator.com',
	'https://steemd.minnowsupportproject.org']

s = Steem(nodes)
```

#### The following errors are encountered:

```
  File "test_connection.py", line 7, in <module>
    s = Steem(nodes)
  File "/home/ger/.local/lib/python3.5/site-packages/steem/steem.py", line 60, in __init__
    steemd_instance=self.steemd, no_broadcast=no_broadcast, **kwargs)
  File "/home/ger/.local/lib/python3.5/site-packages/steem/commit.py", line 96, in __init__
    self.wallet = Wallet(self.steemd, **kwargs)
  File "/home/ger/.local/lib/python3.5/site-packages/steem/wallet.py", line 61, in __init__
    self.prefix = self.steemd.chain_params["prefix"]
  File "/home/ger/.local/lib/python3.5/site-packages/steem/steemd.py", line 70, in chain_params
    chain = props["current_supply"].split(" ")[1]
TypeError: 'NoneType' object is not subscriptable
```

If each node is tested individually rather than as a list other errors occur. In some instances there is no error and the script works as expected. In some instances the system hangs and no exception is caught and no output is given and the script must be ended using ctrl+c. 

### However, it seems that running the script with just one node in the nodes list causes the *least* amount of errors. 

In other instances the exception gets caught in an endless loop and produces errors like this below. This is a small portion of what was an never ending loop of exceptions:


```
Traceback (most recent call last):
  File "/home/ger/.local/lib/python3.5/site-packages/steembase/http_client.py", line 202, in call
    response = self.request(body=body)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 162, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='rpc.steemliberator.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb6f1daec>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xb6f4046c>: Failed to establish a new connection: [Errno 111] Connection refused
```

Coincidentally, if I intentionally enter a spelling mistake into a node address such as "https://steemd.p_rivex.io" it creates the exact same error as above. Also, the script seems to run fine when I leave off the "https://" from certain addresses but not others. For example, if I run the script with the node "

If the script is written to handle an exception like this:

```
#!/usr/bin/python

from steem import Steem

nodes = ['steemd.minnowsupportproject.org']

try:
	s = Steem(nodes)
except Exception as e:
	print (e)
```

It will sometimes hang and give no output, or will give the exception " 'NoneType' object is not subscriptable ", but if I use "steemd.pevo.science" (without https://) it works just fine.

## Running these scripts over and over again produces different results. Sometimes the script will work just fine and no error is given, however today I'm receiving this error pretty much consistently.

**Comment by ArtoLabs** [comment]
BTW I receive these errors using Steem Python Package version number 1.0.1 but I received them using 1.0.0 as well.
