### ISSUE TITLE
Create Post

### ISSUE THREAD

**Issue by RicRock** [steemit/steem-python#24]
Learning my way around and getting the following error:

$ python
 from steem import Steem
 steem = Steem(wif='private_posting_key')
 steem.post(title="Test", body="blank", author="pennterra", tags=['spam','test'], self_vote=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ric/python/lib/python3.6/site-packages/steem/commit.py", line 325, in post
    return self.finalizeOp(ops, author, "posting")
  File "/home/ric/python/lib/python3.6/site-packages/steem/commit.py", line 126, in finalizeOp
    tx.sign()
  File "/home/ric/python/lib/python3.6/site-packages/steem/transactionbuilder.py", line 108, in sign
    raise MissingKeyError
steembase.exceptions.MissingKeyError
 quit()

Am I missing something? or is this an issue?

Thanks
Ric

**Comment by Netherdrake** [comment]
The wif provided is not valid.

Also, its probably more convenient to add it with `steempy addkey <posting_key>`, then you don't have to hardcode keys in code.

**Comment by RicRock** [comment]
Worked perfect.

Thanks for your help!
