### ISSUE TITLE
steempy fails with error RPCErrorRecoverable

### ISSUE THREAD

**Issue by bobinson** [steemit/steem-python#249]
### Version of Python you are running ###

Tried with 3.6.4 and 3.6.5 on macOS 10.13.5 

### Version of steem-python you are running ###

```
steempy  --version
steempy 1.0.1
```

### Expected Behavior ###

setting of nodes should work

### Actual Behavior ###

steempy set nodes https://gtg.steem.house:8090

```
WARNING:root:Retry in 1s -- RPCErrorRecoverable: non-200 response: 400 from None
WARNING:root:Retry in 2s -- RPCErrorRecoverable: non-200 response: 400 from None
WARNING:root:Retry in 3s -- RPCErrorRecoverable: non-200 response: 400 from None
WARNING:root:Retry in 4s -- RPCErrorRecoverable: non-200 response: 400 from None
WARNING:root:Retry in 5s -- RPCErrorRecoverable: non-200 response: 400 from None
WARNING:root:Retry in 6s -- RPCErrorRecoverable: non-200 response: 400 from None
WARNING:root:Retry in 7s -- RPCErrorRecoverable: non-200 response: 400 from None
WARNING:root:Retry in 8s -- RPCErrorRecoverable: non-200 response: 400 from None
WARNING:root:Retry in 9s -- RPCErrorRecoverable: non-200 response: 400 from None
WARNING:root:Retry in 10s -- RPCErrorRecoverable: non-200 response: 400 from None
ERROR:root:Failed after 10 attempts -- RPCErrorRecoverable: non-200 response: 400 from None
Traceback (most recent call last):
  File "/Users/b5413b/.pyenv/versions/3.6.4/bin/steempy", line 11, in <module>
    sys.exit(legacyentry())
  File "/Users/b5413b/.pyenv/versions/3.6.4/lib/python3.6/site-packages/steem/cli.py", line 776, in legacyentry
    steem = stm.Steem(no_broadcast=args.no_broadcast, **options)
  File "/Users/b5413b/.pyenv/versions/3.6.4/lib/python3.6/site-packages/steem/steem.py", line 59, in __init__
    steemd_instance=self.steemd, no_broadcast=no_broadcast, **kwargs)
  File "/Users/b5413b/.pyenv/versions/3.6.4/lib/python3.6/site-packages/steem/commit.py", line 96, in __init__
    self.wallet = Wallet(self.steemd, **kwargs)
  File "/Users/b5413b/.pyenv/versions/3.6.4/lib/python3.6/site-packages/steem/wallet.py", line 61, in __init__
    self.prefix = self.steemd.chain_params["prefix"]
  File "/Users/b5413b/.pyenv/versions/3.6.4/lib/python3.6/site-packages/steem/steemd.py", line 65, in chain_params
    props = self.get_dynamic_global_properties()
  File "/Users/b5413b/.pyenv/versions/3.6.4/lib/python3.6/site-packages/steem/steemd.py", line 419, in get_dynamic_global_properties
    return self.call('get_dynamic_global_properties', api='database_api')
  File "/Users/b5413b/.pyenv/versions/3.6.4/lib/python3.6/site-packages/steembase/http_client.py", line 288, in call
    raise e
  File "/Users/b5413b/.pyenv/versions/3.6.4/lib/python3.6/site-packages/steembase/http_client.py", line 246, in call
    % (response.status, self.hostname))
steembase.exceptions.RPCErrorRecoverable: non-200 response: 400 from None


```### Steps to reproduce ###
just run any command using steempy


### Stack Trace ###

already provided

**Comment by camponez** [comment]
I have the same problem. I can't reset to another node

**Comment by sxiii** [comment]
For me the same behavior. 1.0.2
