### ISSUE TITLE
steem.commit.witness_feed_publish Error

### ISSUE THREAD

**Issue by clayop** [steemit/steem-python#259]
### Version of Python you are running ###
3.5.2

### Version of steem-python you are running ###
1.0.1

### Expected Behavior ###
`steem.commit.witness_feed_publish` publishes a feed

### Actual Behavior ###
```
>>> steem.commit.witness_feed_publish(0.737, account="clayop")
Unexpected exception! Please report at https://github.com/steemit/steem-python/issues -- RPCError: assert_exception from None (Assert Exception:_block_api: block_api_plugin not enabled.) in get_block
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/steem/commit.py", line 966, in witness_feed_publish
    return self.finalizeOp(op, account, "active")
  File "/usr/local/lib/python3.5/dist-packages/steem/commit.py", line 125, in finalizeOp
    tx.appendOps(ops)
  File "/usr/local/lib/python3.5/dist-packages/steem/transactionbuilder.py", line 46, in appendOps
    self.constructTx()
  File "/usr/local/lib/python3.5/dist-packages/steem/transactionbuilder.py", line 90, in constructTx
    ref_block_num, ref_block_prefix = get_block_params(self.steemd)
  File "/usr/local/lib/python3.5/dist-packages/steembase/transactions.py", line 359, in get_block_params
    ref_block = steem.get_block(props["head_block_number"] - 2)
  File "/usr/local/lib/python3.5/dist-packages/steem/steemd.py", line 402, in get_block
    return self.call('get_block', block_num, api='database_api')
  File "/usr/local/lib/python3.5/dist-packages/steembase/http_client.py", line 303, in call
    raise e
  File "/usr/local/lib/python3.5/dist-packages/steembase/http_client.py", line 278, in call
    raise RPCError(detail)
steembase.exceptions.RPCError: assert_exception from None (Assert Exception:_block_api: block_api_plugin not enabled.) in get_block
```

**Comment by clayop** [comment]
Solved. Added `block_api` to plugin in config.ini
