### ISSUE TITLE
Invalid permission on claim_reward_balance

### ISSUE THREAD

**Issue by aaroncox** [steemit/steem-python#5]
I'm getting an error using this method with the proper account/wif combo:

```
Traceback (most recent call last):
  File "/src/test.py", line 11, in <module>
    s.commit.claim_reward_balance(account=account)
  File "/usr/local/lib/python3.5/site-packages/steem/commit.py", line 813, in claim_reward_balance
    return self.finalizeOp(op, account, "posting")
  File "/usr/local/lib/python3.5/site-packages/steem/commit.py", line 125, in finalizeOp
    tx.appendSigner(account, permission)
  File "/usr/local/lib/python3.5/site-packages/steem/transactionbuilder.py", line 45, in appendSigner
    assert permission in ["active", "owner", "poster"], "Invalid permission"
AssertionError: Invalid permission
```

To reproduce this issue, use the following code and environmental variables:

```
from steem import Steem
import os

account        = os.environ['steem_account']
wif            = os.environ['steem_wif']

print(account)
print(wif)

s = Steem(keys=[wif])
s.commit.claim_reward_balance(account=account)
```

I'm not sure why this occurs, but my account does have 2 unusual things which may not have been considered:

- My WIF key is used on multiple accounts, `jesta` and `greymass`
- I have a `posting` authority set to `streemian`

These two things have caused issues in the past, so I figured I'd mention them.

Any ideas?

**Comment by Netherdrake** [comment]
Please upgrade to latest Github master
