### ISSUE TITLE
calls to steemd are not robust in the face of timeouts

### ISSUE THREAD

**Issue by sneak** [steemit/steem-python#55]
```
sneak@rabotnik:~$ steempy listaccounts
Traceback (most recent call last):
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/sneak/Library/Homebrew/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Users/sneak/Library/Homebrew/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Users/sneak/Library/Homebrew/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/sneak/Library/Homebrew/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/Users/sneak/Library/Homebrew/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/sneak/Library/Homebrew/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "/Users/sneak/Library/Homebrew/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/steembase/http_client.py", line 146, in exec
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='steemd.steemit.com', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneak/Library/Homebrew/bin/steempy", line 4, in <module>
    __import__('pkg_resources').run_script('steem==0.18.9', 'steempy')
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/EGG-INFO/scripts/steempy", line 7, in <module>
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/steem/cli.py", line 1137, in legacy
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/steem/wallet.py", line 368, in getAccounts
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/steem/wallet.py", line 331, in getAccount
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/steem/wallet.py", line 322, in getAccountFromPublicKey
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/steembase/http_client.py", line 167, in exec
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/steembase/http_client.py", line 186, in exec
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/steembase/http_client.py", line 206, in _return
steembase.exceptions.RPCError: 10 assert_exception: Assert Exception
false: database_api::get_key_references has been deprecated. Please use account_by_key_api::get_key_references instead.
    {}
    th_a  database_api.cpp:402 get_key_references

    {"call.method":"get_key_references","call.params":[["STM...redacted..."]]}
    th_a  websocket_api.cpp:124 on_message
sneak@rabotnik:~$ 
```

**Comment by roadscape** [comment]
Error retries have been revamped recently and I see `ReadTimeoutError` explicitly listed as recoverable, so I believe this issue is resolved.
