### ISSUE TITLE
ValueError fatal in steempy newaccount

### ISSUE THREAD

**Issue by sneak** [steemit/steem-python#57]
```
sneak@rabotnik:~$ steempy newaccount --account creatoraccount --fee 6 newaccountname
New Account Passphrase: 
Confirm New Account Passphrase: 
Passphrase: 
Traceback (most recent call last):
  File "/Users/sneak/Library/Homebrew/bin/steempy", line 4, in <module>
    __import__('pkg_resources').run_script('steem==0.18.9', 'steempy')
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/EGG-INFO/scripts/steempy", line 7, in <module>
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/steem/cli.py", line 1309, in legacy
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/steem/commit.py", line 528, in create_account
  File "/Users/sneak/Library/Homebrew/lib/python3.6/site-packages/steem-0.18.9-py3.6.egg/steem/amount.py", line 11, in __init__
ValueError: not enough values to unpack (expected 2, got 1)
sneak@rabotnik:~$ 
```

**Comment by sneak** [comment]
ahh, fee needs to be specified as "6 STEEM" and not 6.  error should be better.

**Comment by SchroSct** [comment]
yes, holy moley
