### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by clayop** [steemit/steem-python#92]
Ubuntu 17.10
Python 3.6.3

~~~
    Installed /tmp/pip-build-pap1j575/steem/.eggs/pytest_pylint-0.7.1-py3.6.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pap1j575/steem/setup.py", line 15, in <module>
        tests_require=package_meta.default_requirements+package_meta.dev_requirements)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 325, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 446, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 858, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'pytest' distribution was not found and is required by the application
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pap1j575/steem/
~~~

**Comment by clayop** [comment]
Can be resolved by
`pip3 install -U pytest`

I will test clean installation cases and will PR the documentation

**Comment by chenlocus** [comment]
Using cached steem-0.18.103.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\holroyd\AppData\Local\Temp\pip-build-tqwdzgty\steem\setup.py", line 8, in <module>
        import package_meta # this is a simple tool for loading metadata from Pipfile and other places
      File "C:\Users\holroyd\AppData\Local\Temp\pip-build-tqwdzgty\steem\package_meta.py", line 10, in <module>
        from setuptools.config import read_configuration
    ModuleNotFoundError: No module named 'setuptools.config'

**Comment by bobinson** [comment]
facing same issue

**Comment by cyon1c** [comment]
[Setuptools is missing](https://stackoverflow.com/questions/14426491/python-3-importerror-no-module-named-setuptools).
